### ISSUE TITLE
Make WindowsVault

### ISSUE THREAD

**Issue by ghost** [guervild/BOFs#2]
x86_64-w64-mingw32-gcc -o WindowsVault.x64.o  -c WindowsVault.c
In file included from WindowsVault.c:1:
WindowsVault.h:7:10: fatal error: VersionHelpers.h: No such file or directory
    7 | #include <VersionHelpers.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1

Windows:
Microsoft (R) Program Maintenance Utility Version 14.29.30133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

makefile(1) : fatal error U1033: syntax error : '=' unexpected
Stop.

**Comment by ceramic-skate0** [comment]
cl /c /GS- WindowsVault.c /FwindowsVault.x64.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

WindowsVault.c


Appears to have compiled. perhaps nmake file for VS?

**Comment by guervild** [comment]
Hello

Thanks for the issue. I removed the unused import in the last commit (https://github.com/guervild/BOFs/commit/1136c6ab8ff08b21899ab44582181a72c3583b8a).

Let met know if there is still any issue with the BOF.

Thanks

**Comment by ghost** [comment]
Thanks!

Looks like changes allows it to compile.
 
Also i had it compiling without errors as it was in Visual Studio (didnt run test yet).
```
cl /GS- /nologo /Od /Oi /c windowsVault.c /FoWindowsVault.x86.o
cl /GS- /nologo /Od /Oi /c windowsVault.c /FoWindowsVault.x64.o
```
